steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','asia-south1-docker.pkg.dev/$pysellers/hrms-repo/hrms','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia-south1-docker.pkg.dev/$pysellers/hrms-repo/hrms']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - hrms-service
  - --image=asia-south1-docker.pkg.dev/$pysellers/hrms-repo/hrms
  - --region=asia-south1
  - --platform=managed
  - --allow-unauthenticated
